### PR TITLE
fix: default query usage

### LINKED ISSUE #855: defaultQuery support in search component
**Issue Type:**
Enhancement

**Platform:**
All

**Description:**
This will enable customising only the suggestions query, and not the component's search query. With our current behavior, we use the same query to fetch suggestions and same query to fire the search query after the suggestion is selected - which can be updated via `customQuery`.

This will essentially enable users to customise both the queries separately.

### PR DESCRIPTION
**Pull request by bietkul**
This PR contains the following things
- Apply the `query` option from `defaultQuery` in search & list components
- Add `defaultQuery` support in search components
- Make `defaultQuery` and `customQuery` prop reactive i.e prop change will trigger a new query.

Fixes #855, #867, #852, #531, #900

### CODE REVIEW

File: packages/web/src/components/list/MultiList.js [hunk 1]
```diff
@@ -365,6 +378,29 @@ class MultiList extends Component {
 		});
 	};
 
+	updateDefaultQuery = (queryOptions) => {
```
Comment (lakhansamani) [inline packages/web/src/components/list/MultiList.js:381]: Seems like repeating coding, can we make common util function for `updateDefaultQuery`?

File: packages/web/src/utils/index.js [hunk 2]
```diff
@@ -55,3 +56,18 @@ export const hasCustomRenderer = (props = {}) => {
...
 export const isEvent = candidate =>
 	!!(candidate && candidate.stopPropagation && candidate.preventDefault);
+/**
+ * To check if two functions are identical
+ */
+export const isIdentical = (a, b) => {
+	if (a === b) {
+		return true;
+	}
+	if (typeof a === 'function' && typeof b === 'function') {
```
Comment (lakhansamani) [inline packages/web/src/utils/index.js:64]: Won't the above condition already check type for functions, since we are using `===`. I guess it might never go into this condition, as it will return true from line 64?

**Review by lakhansamani — CHANGES_REQUESTED** [review]

File: packages/web/src/utils/index.js (hunk 2 above)
Comment (bietkul) [reply packages/web/src/utils/index.js:64]: The first condition is just to cover the case when both have `undefined` or `null` value.
The second condition compares(deeply) the returned value of functions to avoid the infinite loop when someone uses arrow functions.

Comment (lakhansamani) [reply packages/web/src/utils/index.js:64]: I see in that case we can make the first condition more clear by writing
```
if (!a && !b) return true
```

File: packages/web/src/components/list/MultiList.js (hunk 1 above)
Comment (bietkul) [reply packages/web/src/components/list/MultiList.js:381]: cool, will do something.

File: packages/web/src/utils/index.js (hunk 2 above)
Comment (bietkul) [reply packages/web/src/utils/index.js:64]: agree

File: packages/web/src/components/search/CategorySearch.js [hunk 3]
```diff
@@ -395,34 +422,60 @@ class CategorySearch extends Component {
...
-			this.updateQuery(this.internalComponent, value, this.props);
+			this.updateDefaultQuery(value, this.props);
 		} else {
-			this.updateQuery(this.props.componentId, value, this.props);
+			this.updateQuery(value, this.props);
 		}
 	}, this.props.debounce);
 
-	updateQuery = (componentId, value, props, category) => {
+	updateDefaultQuery = (value, props, category = this.state.currentCategory) => {
```
Comment (lakhansamani) [inline packages/web/src/components/search/CategorySearch.js:431]: How about using `defaultInternalQuery` here with one more param, i.e. `aggsQuery`?

File: packages/web/src/components/search/DataSearch.js [hunk 4]
```diff
@@ -343,22 +353,44 @@ class DataSearch extends Component {
...
-			this.updateQuery(this.internalComponent, value, this.props);
+			this.updateDefaultQuery(value, this.props);
 		} else {
-			this.updateQuery(this.props.componentId, value, this.props);
+			this.updateQuery(value, this.props);
 		}
 	}, this.props.debounce);
 
-	updateQuery = (componentId, value, props) => {
+	updateDefaultQuery = (value, props) => {
```
Comment (lakhansamani) [inline packages/web/src/components/search/DataSearch.js:362]: Same here, we can use`updateInternalQuery`. To make function simpler we can add switch cases over there for component types.

File: packages/web/src/components/search/DataSearch.js [hunk 5]
```diff
@@ -343,22 +353,44 @@ class DataSearch extends Component {
...
+		}
+		props.setQueryOptions(this.internalComponent, {
+			...this.queryOptions,
+			...defaultQueryOptions,
+		});
+		props.updateQuery({
+			componentId: this.internalComponent,
+			query,
+			value,
+			componentType: 'DATASEARCH',
```
Comment (lakhansamani) [inline packages/web/src/components/search/DataSearch.js]: Can we make ENUM for all component type we have and use it? WDYT?

**Review by lakhansamani — CHANGES_REQUESTED** [review]

File: packages/web/src/components/search/DataSearch.js (hunk 4 above)
Comment (bietkul) [reply packages/web/src/components/search/DataSearch.js:362]: Things are different with search components.

File: packages/web/src/components/search/DataSearch.js (hunk 5 above)
Comment (bietkul) [reply packages/web/src/components/search/DataSearch.js]: > Can we make ENUM for all component type we have and use it? WDYT?

At that time it may need some extra work since they have been defined in `reactivecore` so we have to export them and use it here.
I think it's ok to just use strings, we can do that code refactoring later at some time.
