### PR TITLE
fix(web): multi-range values not refreshing on browser back and forward

### LINKED ISSUE #1291: URLParams with ReactiveList
**Affected Projects**
React

**Library Version:** x.y.z
3.1.2

**Describe the bug**
URL param is not getting removed when using browser navigation

**To Reproduce**
1. Set the `URLParams` as `true` in `ReactiveList` and click on a page.
2. Go back and URL param is not getting removed

https://codesandbox.io/s/reverent-driscoll-88fqw

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by ShahAnuj2610**
fixes #1291

### CODE REVIEW

File: packages/web/src/components/range/MultiRange.js [hunk 1]
```diff
@@ -26,12 +26,7 @@ import types from '@appbaseio/reactivecore/lib/utils/types';
 import Title from '../../styles/Title';
 import Container from '../../styles/Container';
 import { UL, Checkbox } from '../../styles/FormControlList';
-import {
-	connect,
-	getRangeQueryWithNullValues,
-	getValidPropsKeys,
-	parseValueArray,
-} from '../../utils';
+import { connect, getRangeQueryWithNullValues, getValidPropsKeys, parseValueArray } from '../../utils';
```
Comment (bietkul) [inline packages/web/src/components/range/MultiRange.js]: @ShahAnuj2610 Please fix these formatting issues.

**Review by bietkul — CHANGES_REQUESTED** [review]

File: packages/web/src/components/range/MultiRange.js (hunk 1 above)
Comment (ShahAnuj2610) [reply packages/web/src/components/range/MultiRange.js]: done

**Review by bietkul — APPROVED** [review]
