### PR TITLE
fix: ResultList, ResultCard scroll-container height

### LINKED ISSUE #223: Typescript support
**Issue Type:enhancement**

**Description:**

Any plan to support  [type definition file](https://github.com/DefinitelyTyped/DefinitelyTyped) for Typescript?
**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

Thanks!

### PR DESCRIPTION
**Pull request by dhruvdutt**
Fixes [#223](https://github.com/appbaseio/reactivebase/issues/223)

### CODE REVIEW

**Comment by dhruvdutt** [comment]
@metagrover Please review.

File: app/actuators/ResultCard.js [hunk 1]
```diff
@@ -151,7 +151,10 @@ export default class ResultCard extends Component {
 			const scrollFlag = scrollElement.scrollHeight > resultElement.clientHeight;
 			if (!flag && !scrollFlag && scrollElement && !this.props.pagination) {
 				const scrollHeight = resultElement.clientHeight - 100;
-				if (scrollHeight > 0) {
+				if (this.props.scrollOnTarget) {
+					scrollElement.style.height = "auto";
+					scrollElement.style.paddingBottom = 0;
```
Comment (metagrover) [inline app/actuators/ResultCard.js]: No need to specify the paddingBottom here

Comment (dhruvdutt) [reply app/actuators/ResultCard.js]: @metagrover Updated.
