### PR TITLE
fix(web): customQuery and defaultQuery frequently called

### LINKED ISSUE #1403: MultiList frequently calls customQuery with undefined value and props.
**Affected Projects**
React

**Library Version:** x.y.z
```
  "@appbaseio/reactivecore": "^9.0.3",
  "@appbaseio/reactivesearch": "^3.2.4",
```

**Describe the bug**
`MultiList` frequently calls customQuery with undefined value and props.

**To Reproduce**
```jsx
<MultiList
  dataField="type"
  customQuery={(value, props) => {
    console.log(value, props);
    return { query: { terms: { [props.dataField]: value } } };
  }}
/>
```

**Expected behavior**
`customQuery` is called with `value` and `props` as defined in documentation.

**Additional context**
This is caused by the MultiList `componentDidUpdate` using isIdentical to compare the `customQuery` and `defaultQuery` props. The `isIdentical` helper function checks if the props are functions and if they are, it runs the functions with no arguments.

### PR DESCRIPTION
**Pull request by ShahAnuj2610**
fixes https://github.com/appbaseio/reactivesearch/issues/1403

## Dependent PR
https://github.com/appbaseio/reactivecore/pull/73

## Fix
Right now query is not compared gracefully, which leads to crashing the component. Check this: https://codesandbox.io/s/stupefied-herschel-lcyge?file=/src/index.js:586-767. This is an util to compare **defaultQuery** and **customQuery** gracefully.

Also in **componentDidUpdate** or wherever when we're comparing queries, the `props.defaultQuery` or `props.customQuery` should not get called, instead a copy of that fn should be called. That is also fixed.

## Demo video
- Basic testing - https://www.loom.com/share/3a4512436c2f433c971d77baad14c58e
- Testing reactiveness - https://www.loom.com/share/75cc4a1c6caf4132beca8f048ecb44cd
- Test `defaultQuery` and `customQuery` with `MultiList` -> https://recordit.co/nSp92Onsuv

### CODE REVIEW

File: packages/web/src/utils/index.js [hunk 1]
```diff
@@ -130,3 +130,14 @@ export function parseValueArray(originalArr = [], currentValue) {
 export function escapeRegExp(string) {
 	return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); // $& means the whole matched string
 }
+
+/**
+ * @param {Object} props
+ * @param {Object} prevProps
+ * @param {'defaultQuery' | 'customQuery'} key
+ */
+export const isQueryIdentical = (props, prevProps, key) => {
```
Comment (bietkul) [inline packages/web/src/utils/index.js]: @ShahAnuj2610 Initialize `props` & `prevProps` as an empty object.

**Review by bietkul — CHANGES_REQUESTED** [review]

File: packages/web/src/utils/index.js (hunk 1 above)
Comment (ShahAnuj2610) [reply packages/web/src/utils/index.js]: yes

File: packages/web/src/utils/index.js [hunk 2]
```diff
@@ -130,3 +130,17 @@ export function parseValueArray(originalArr = [], currentValue) {
...
+ * @param {Object} prevProps
+ * @param {'defaultQuery' | 'customQuery'} key
+ */
+export const isQueryIdentical = (props = {}, prevProps = {}, key) => {
+	if (!key) return true;
+	if (typeof props[key] !== 'function' || typeof prevProps[key] !== 'function') return true;
+	// to not call original defaultQuery and customQuery, as here we are only comparing
+	const prevQuery = () => prevProps[key];
+	const nextQuery = () => props[key];
+	return isEqual(nextQuery(props.value, props), prevQuery(prevProps.value, prevProps));
```
Comment (bietkul) [inline packages/web/src/utils/index.js]: @ShahAnuj2610 You'll not find `value` in the props, you need to pass the current value from the component.

**Review by bietkul — CHANGES_REQUESTED** [review]

File: packages/web/src/utils/index.js (hunk 2 above)
Comment (ShahAnuj2610) [reply packages/web/src/utils/index.js]: @bietkul what would happen in case of a controlled component?

Comment (bietkul) [reply packages/web/src/utils/index.js]: @ShahAnuj2610 Just use the `value` from the state.
Check the logic where we evaluate the `customQuery` in `updateQuery` method.

Comment (ShahAnuj2610) [reply packages/web/src/utils/index.js]: okay, doing it.

Comment (ShahAnuj2610) [reply packages/web/src/utils/index.js]: also @bietkul since we're comparing queries, it would be compared wrt to  **this.state.currentValue** and not **prevState.currentValue**.

E.g. it would be 

```
isEqual(
nextQuery(this.state.currentValue, props), 
prevQuery(this.state.currentValue, prevProps)
);
```

and not

```
isEqual(
nextQuery(this.state.currentValue, props), 
prevQuery(prevState.currentValue, prevProps)
);
```

Comment (ShahAnuj2610) [reply packages/web/src/utils/index.js]: @bietkul have fixed it

File: packages/web/src/components/list/MultiDropdownList.js [hunk 3]
```diff
@@ -153,12 +158,12 @@ class MultiDropdownList extends Component {
 			}
 		});
 		// Treat defaultQuery and customQuery as reactive props
-		if (!isIdentical(this.props.defaultQuery, prevProps.defaultQuery)) {
+		if (!isQueryIdentical([], this.props, prevProps, 'defaultQuery')) {
```
Comment (bietkul) [inline packages/web/src/components/list/MultiDropdownList.js]: @ShahAnuj2610 In the below code, you're passing value but here you're passing an empty array as value.

File: packages/web/src/components/list/MultiList.js [hunk 4]
```diff
@@ -161,12 +161,12 @@ class MultiList extends Component {
 			}
 		});
 		// Treat defaultQuery and customQuery as reactive props
-		if (!isIdentical(this.props.defaultQuery, prevProps.defaultQuery)) {
+		if (!isQueryIdentical([], this.props, prevProps, 'defaultQuery')) {
```
Comment (bietkul) [inline packages/web/src/components/list/MultiList.js]: @ShahAnuj2610 Same issue is here

File: packages/web/src/components/list/SingleDropdownList.js [hunk 5]
```diff
@@ -130,13 +135,13 @@ class SingleDropdownList extends Component {
 		);
 
 		// Treat defaultQuery and customQuery as reactive props
-		if (!isIdentical(this.props.defaultQuery, prevProps.defaultQuery)) {
+		if (!isQueryIdentical('', this.props, prevProps, 'defaultQuery')) {
```
Comment (bietkul) [inline packages/web/src/components/list/SingleDropdownList.js]: same here

File: packages/web/src/components/list/SingleList.js [hunk 6]
```diff
@@ -134,13 +134,13 @@ class SingleList extends Component {
 		});
 
 		// Treat defaultQuery and customQuery as reactive props
-		if (!isIdentical(this.props.defaultQuery, prevProps.defaultQuery)) {
+		if (!isQueryIdentical('', this.props, prevProps, 'defaultQuery')) {
```
Comment (bietkul) [inline packages/web/src/components/list/SingleList.js]: same here

**Review by bietkul — CHANGES_REQUESTED** [review]

File: packages/web/src/components/list/MultiDropdownList.js (hunk 3 above)
Comment (ShahAnuj2610) [reply packages/web/src/components/list/MultiDropdownList.js]: @bietkul an open question. We're updating query with `[]` value, so should that value be passed or currentValue?

https://github.com/appbaseio/reactivesearch/blob/87a201d95d396944dc85e6d8686a9593ddef1d5f/packages/web/src/components/list/MultiDropdownList.js#L163

Comment (bietkul) [reply packages/web/src/components/list/MultiDropdownList.js]: @ShahAnuj2610 Use `currentValue`, it'll be updated when you set the `query`.

Comment (ShahAnuj2610) [reply packages/web/src/components/list/MultiDropdownList.js]: @bietkul fixing it in all components. Since all of them are either passing `''` or `[]` in **updateQuery**

**Comment by bietkul** [comment]
@ShahAnuj2610 What's the update here?

**Comment by ShahAnuj2610** [comment]
> @ShahAnuj2610 What's the update here?

@bietkul value changes have been done for search and range components. Working on list components.

**Comment by ShahAnuj2610** [comment]
@bietkul lmk, if this diff looks good for MultiList, I can do the same for other list components

```diff
Index: packages/web/src/components/list/MultiList.js
===================================================================
--- packages/web/src/components/list/MultiList.js	(revision 87a201d95d396944dc85e6d8686a9593ddef1d5f)
+++ packages/web/src/components/list/MultiList.js	(date 1587968744781)
@@ -112,9 +112,7 @@
 		});
 		checkPropChange(this.props.react, prevProps.react, () => this.setReact(this.props));
 		checkPropChange(this.props.options, prevProps.options, () => {
-			const {
-				showLoadMore, dataField, options,
-			} = this.props;
+			const { showLoadMore, dataField, options } = this.props;
 			if (showLoadMore && options && options[dataField]) {
 				const { buckets } = options[dataField];
 				const after = options[dataField].after_key;
@@ -160,22 +158,24 @@
 				);
 			}
 		});
+		const valueArray
+			= typeof this.state.currentValue === 'object' ? Object.keys(this.state.currentValue) : [];
 		// Treat defaultQuery and customQuery as reactive props
-		if (!isQueryIdentical([], this.props, prevProps, 'defaultQuery')) {
+		if (!isQueryIdentical(valueArray, this.props, prevProps, 'defaultQuery')) {
 			this.updateDefaultQuery();
-			this.updateQuery([], this.props);
+			this.updateQuery(valueArray, this.props);
 		}
 
-		if (!isQueryIdentical(Object.keys(this.state.currentValue), this.props, prevProps, 'customQuery')) {
-			this.updateQuery(Object.keys(this.state.currentValue), this.props);
+		if (!isQueryIdentical(valueArray, this.props, prevProps, 'customQuery')) {
+			this.updateQuery(valueArray, this.props);
 		}
 
 		checkSomePropChange(this.props, prevProps, ['dataField', 'nestedField'], () => {
 			this.updateQueryOptions(this.props);
-			this.updateQuery(Object.keys(this.state.currentValue), this.props);
+			this.updateQuery(valueArray, this.props);
 		});
 
-		let selectedValue = Object.keys(this.state.currentValue);
+		let selectedValue = valueArray;
 		const { selectAllLabel } = this.props;
 
 		if (selectAllLabel) {
@@ -197,7 +197,7 @@
 			} else if (onChange) {
 				onChange(this.props.selectedValue || null);
 			} else {
-				const selectedListItems = Object.keys(this.state.currentValue);
+				const selectedListItems = valueArray;
 				this.setValue(selectedListItems, true);
 			}
 		}
@@ -386,7 +386,7 @@
 			updateCustomQuery(props.componentId, props, value);
 		}
 		props.setQueryOptions(props.componentId, {
-			...MultiList.generateQueryOptions(props, this.state.prevAfter),
+			...MultiList.generateQueryOptions(props, this.state.prevAfter, this.state.currentValue),
 			...customQueryOptions,
 		});
 
@@ -407,16 +407,21 @@
 			queryOptions,
 			Object.keys(this.state.currentValue),
 			this.props,
-			MultiList.generateQueryOptions(this.props, this.state.prevAfter),
+			MultiList.generateQueryOptions(
+				this.props,
+				this.state.prevAfter,
+				this.state.currentValue,
+			),
 			null,
 		);
 	};
 
-	static generateQueryOptions(props, after) {
+	static generateQueryOptions(props, after, value = {}) {
 		const queryOptions = getQueryOptions(props);
+		const valueArray = Object.keys(value);
 		return props.showLoadMore
-			? getCompositeAggsQuery(queryOptions, props, after)
-			: getAggsQuery(queryOptions, props);
+			? getCompositeAggsQuery(valueArray, queryOptions, props, after)
+			: getAggsQuery(valueArray, queryOptions, props);
 	}
 
 	updateQueryOptions = (props, addAfterKey = false) => {
@@ -430,6 +435,7 @@
 		const queryOptions = MultiList.generateQueryOptions(
 			props,
 			addAfterKey ? this.state.after : {},
+			this.state.currentValue,
 		);
 		if (props.defaultQuery) {
 			this.updateDefaultQuery(queryOptions);
@@ -446,7 +452,11 @@
 	};
 
 	handleLoadMore = () => {
-		const queryOptions = MultiList.generateQueryOptions(this.props, this.state.after);
+		const queryOptions = MultiList.generateQueryOptions(
+			this.props,
+			this.state.after,
+			this.state.currentValue,
+		);
 		this.props.loadMore(this.props.componentId, queryOptions);
 	};
 
```

**Comment by ShahAnuj2610** [comment]
@bietkul have done the changes and attached test video for this and it's dependent PR

**Review by bietkul — APPROVED** [review]
