### PR TITLE
web: ToggleButton allow customizable button

### LINKED ISSUE #262: FeatureRequest: Allow customizable buttons in ToggleButton
**Issue Type:**
enhancement

**Description:**

Add the ability to customize individual buttons in ToggleButtons. The goal is to be able to customize the style of each button, as well as optionally add icons or other html elements to them. This could be accomplished in several ways, including adding the ability to set classNames on individual buttons, as well as adding additional html.

So, a start would be something like adding a className, but it has limited power:
```jsx
<ToggleButton
  componentId="MeetupTops"
  dataField="group_topics.topic_name.raw"
  data={
    [{"label": "Social",   className: "red-btn",  "value": "Social"},
     {"label": "Travel",   className: "green-btn", "value": "Travel"},
     {"label": "Outdoors",  className: "blue-btn", "value": "Outdoors"}]
  }
/>
```
A more advanced approach may be allowing html in the label section:
```jsx
<ToggleButton
componentId="category"
dataField="category.raw"
data={[
{"label": (<span className="alpha"><i class="alpha-icon"></i>Alpha</span>),   "value": "alpha"},
{"label": (<span className="beta"><i class="beta-icon"></i>Beta</span>),   "value": "beta"}]}/>
```

This currently causes the following error:
```
Warning: flattenChildren(...): Encountered two children with the same key, `1:$[object Object]`. Child keys must be unique; when two children share a key, only the first child will be used.
    in div (created by ToggleButton)
    in ToggleButton (created by Connect(ToggleButton))
    in Connect(ToggleButton) (created by App)
    in div (created by App)
    in div (created by Styled(div))
    in Styled(div) (created by URLParamsProvider)
    in URLParamsProvider (created by Connect(URLParamsProvider))
    in Connect(URLParamsProvider) (created by ReactiveBase)
    in Provider (created by ReactiveBase)
    in ThemeProvider (created by ReactiveBase)
    in ReactiveBase (created by App)
    in App
```

Perhaps some combination of the two above techniques?

### PR DESCRIPTION
**Pull request by dhruvdutt**
Fixes #262

### CODE REVIEW

File: packages/web/src/components/basic/ToggleButton.js [hunk 1]
```diff
@@ -173,12 +173,12 @@ class ToggleButton extends Component {
...
 				}
 				{this.props.data.map((item) => {
-					const isSelected = this.state.currentValue.some(value => value.label === item.label);
+					const isSelected = this.state.currentValue.some(value => value.value === item.value);
 					return (
 						<Button
 							className={`${getClassName(this.props.innerClass, 'button')} ${isSelected ? 'active' : ''}`}
 							onClick={() => this.handleToggle(item)}
-							key={item.label}
+							key={item.value}
```
Comment (dhruvdutt) [inline packages/web/src/components/basic/ToggleButton.js]: @metagrover @divyanshu013 
If we allow duplicate `value`, what should this be changed to?

Comment (metagrover) [reply packages/web/src/components/basic/ToggleButton.js]: Ideally, you shouldn't have duplicate `value` keys in the `data` prop. So, we can ignore this until a use-case comes up.
